cfm:
  unet_dim: 512
  unet_depth: 6
  unet_heads: 8
  unet_dropout_rate: 0.0
  audio_latent_dim: null
  use_conv_layer: false
  use_sos_token: false
  sigma: 1.0e-5
  uncond_prob: 0.0
  expansion_factor: null
  mel_channels: 100
  learned_prior: false
  is_causal: false
  decoder_type: "dit"


